id: P008080
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17841
  title: གསུང་འབུམ། ཡེ་ཤེས་རྒྱ་མཚོ།
  author: ''
  volumes:
    ddd9b150c81d4a0591fa9451f5ff5395:
      image_group_id: I8LS17867
      title: ''
      volume_number: 1
      total_pages: 802
    df5bdebe591549ad8c620983da1d4e67:
      image_group_id: I8LS17868
      title: ''
      volume_number: 2
      total_pages: 882
    6f273e336eaf435c8e40b08f0f4c9238:
      image_group_id: I8LS17869
      title: ''
      volume_number: 3
      total_pages: 778
    7377b63a6ea04584bfb3e6be4b90a226:
      image_group_id: I8LS17870
      title: ''
      volume_number: 4
      total_pages: 857
    94c29dbdf035421d8ecec2f0982a6262:
      image_group_id: I8LS17871
      title: ''
      volume_number: 5
      total_pages: 758
ebook_metadata:
  title: གསུང་འབུམ། ཡེ་ཤེས་རྒྱ་མཚོ།
  author: ''
  sku: P008080
  cover: cover.jpg
  layers:
  - pagination
