id: P008080
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 13:00:05.862918
source_metadata:
  id: bdr:W8LS17841
  title: གསུང་འབུམ། ཡེ་ཤེས་རྒྱ་མཚོ།
  author: ''
  volumes:
    a8a8a70f10994bc898076b284a42ced2:
      image_group_id: I8LS17867
      title: Volume 1 of gsung 'bum/ ye shes rgya mtsho/
      volume_number: 1
      total_pages: 802
      base_file: v001.txt
    378e2a0c8c1f4fa8b1f4d04f3a3defe1:
      image_group_id: I8LS17868
      title: Volume 2 of gsung 'bum/ ye shes rgya mtsho/
      volume_number: 2
      total_pages: 882
      base_file: v002.txt
    cb550d5911ef43d39a0a79db9c57a39e:
      image_group_id: I8LS17869
      title: Volume 3 of gsung 'bum/ ye shes rgya mtsho/
      volume_number: 3
      total_pages: 778
      base_file: v003.txt
    b84a471965cb48fba63754305bf23fa5:
      image_group_id: I8LS17870
      title: Volume 4 of gsung 'bum/ ye shes rgya mtsho/
      volume_number: 4
      total_pages: 857
      base_file: v004.txt
    ed506846139048a096dbf2eba61273a6:
      image_group_id: I8LS17871
      title: Volume 5 of gsung 'bum/ ye shes rgya mtsho/
      volume_number: 5
      total_pages: 758
      base_file: v005.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
