id: I186827A6
legacy_id: P008080
ocr_import_info:
  bdrc_scan_id: W8LS17841
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T15:06:13'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-04T04:00:09.027241+00:00'
last_modified: 2022-09-04 12:02:05.408428
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W8LS17841
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW8LS17841
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཡེ་ཤེས་རྒྱ་མཚོ།
  author: ཡེ་ཤེས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.6433266952277827
  ocr_word_median_confidence_index: 0.699999988079071
quality: null
bases:
  I8LS17870:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17870
      total_pages: 857
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I8LS17870.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7557365654308112
    legacy_id: v004
  I8LS17867:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17867
      total_pages: 802
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I8LS17867.txt
    statistics:
      ocr_word_median_confidence_index: 0.7599999904632568
      ocr_word_mean_confidence_index: 0.686814467220418
    legacy_id: v001
  I8LS17869:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17869
      total_pages: 778
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I8LS17869.txt
    statistics:
      ocr_word_median_confidence_index: 0.6499999761581421
      ocr_word_mean_confidence_index: 0.6166300014771907
    legacy_id: v003
  I8LS17871:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17871
      total_pages: 758
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I8LS17871.txt
    statistics:
      ocr_word_median_confidence_index: 0.5899999737739563
      ocr_word_mean_confidence_index: 0.5792118922272015
    legacy_id: v005
  I8LS17868:
    source_metadata:
      id: http://purl.bdrc.io/resource/I8LS17868
      total_pages: 882
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I8LS17868.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.592673288289795
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
